In [1]:
from dl_helper.rl.custom_imitation_module.dataset import LobTrajectoryDataset

data_config = {
    'his_len': 10,# 每个样本的 历史数据长度
    'need_cols': [item for i in range(1) for item in [f'BASE卖{i+1}价', f'BASE卖{i+1}量', f'BASE买{i+1}价', f'BASE买{i+1}量']],
}

data_dict_folder = r'D:\L2_DATA_T0_ETF\train_data\RAW\BC_train_data_20250810\data_dict'
dataset = LobTrajectoryDataset(data_folder= data_dict_folder, data_config = data_config)
print(f'训练样本数量: {len(dataset)}')
dataset[0]

159941 空仓使用样本数量: 0
159941 持仓使用样本数量: 40
159941 样本总数: 40
513060 空仓使用样本数量: 22
513060 持仓使用样本数量: 58
513060 样本总数: 80
513180 空仓使用样本数量: 128
513180 持仓使用样本数量: 118
513180 样本总数: 246
513330 空仓使用样本数量: 22
513330 持仓使用样本数量: 60
513330 样本总数: 82
[train] 样本数量: 448
训练样本数量: 448


(array([ 6.3907748e-01,  3.0338943e-01,  4.9655718e-01,  1.8467782e-01,
         6.3907748e-01,  3.8333428e-01,  4.9655718e-01,  1.9739214e-01,
         6.3907748e-01,  3.3972171e-01,  4.9655718e-01,  5.7886343e-02,
         4.9655718e-01,  9.2489630e-02,  3.5403687e-01,  8.1047583e-01,
         4.9655718e-01,  3.2489952e-01,  3.5403687e-01,  8.0732548e-01,
         4.9655718e-01, -1.6096984e-01,  3.5403687e-01,  7.7891612e-01,
         4.9655718e-01, -1.2439682e-01,  3.5403687e-01,  7.8436691e-01,
         6.3907748e-01,  5.8983827e-01,  4.9655718e-01, -1.5871543e-01,
         6.3907748e-01,  6.4759696e-01,  4.9655718e-01, -5.3120881e-01,
         4.9655718e-01, -5.5779505e-01,  3.5403687e-01,  8.6562419e-01,
         0.0000000e+00,  9.7838384e-01,  0.0000000e+00,  1.2401000e+04],
       dtype=float32),
 np.float32(0.0))

In [2]:
val_dataset = LobTrajectoryDataset(data_folder= data_dict_folder, data_config = data_config, data_type='val')
print(f'验证集样本数量: {len(val_dataset)}')
val_dataset[0]

[val] 样本数量: 35710
验证集样本数量: 35710


(array([ 7.8160632e-01,  2.4426597e-01,  6.3907748e-01,  6.3885766e-01,
         7.8160632e-01, -1.5606748e-01,  6.3907748e-01,  6.1887777e-01,
         7.8160632e-01, -1.3535701e-01,  6.3907748e-01,  6.2049788e-01,
         7.8160632e-01, -1.2918614e-01,  6.3907748e-01,  5.9981465e-01,
         7.8160632e-01, -5.5973127e-02,  6.3907748e-01,  5.8912241e-01,
         7.8160632e-01, -1.8334653e-02,  6.3907748e-01,  5.8110529e-01,
         7.8160632e-01,  5.4321772e-01,  6.3907748e-01,  5.9356213e-01,
         7.8160632e-01,  5.4378080e-01,  6.3907748e-01,  8.3645499e-01,
         7.8160632e-01,  6.2877035e-01,  6.3907748e-01,  8.2431626e-01,
         7.8160632e-01,  6.7482996e-01,  6.3907748e-01,  7.9288846e-01,
         0.0000000e+00,  9.8368686e-01,  0.0000000e+00,  1.2401000e+04],
       dtype=float32),
 np.float32(1.0))

In [3]:
val_dataset = LobTrajectoryDataset(data_folder= data_dict_folder, data_config = data_config, data_type='test')
print(f'验证集样本数量: {len(val_dataset)}')
val_dataset[0]

[test] 样本数量: 35710
验证集样本数量: 35710


(array([ 7.8160632e-01,  2.4426597e-01,  6.3907748e-01,  6.3885766e-01,
         7.8160632e-01, -1.5606748e-01,  6.3907748e-01,  6.1887777e-01,
         7.8160632e-01, -1.3535701e-01,  6.3907748e-01,  6.2049788e-01,
         7.8160632e-01, -1.2918614e-01,  6.3907748e-01,  5.9981465e-01,
         7.8160632e-01, -5.5973127e-02,  6.3907748e-01,  5.8912241e-01,
         7.8160632e-01, -1.8334653e-02,  6.3907748e-01,  5.8110529e-01,
         7.8160632e-01,  5.4321772e-01,  6.3907748e-01,  5.9356213e-01,
         7.8160632e-01,  5.4378080e-01,  6.3907748e-01,  8.3645499e-01,
         7.8160632e-01,  6.2877035e-01,  6.3907748e-01,  8.2431626e-01,
         7.8160632e-01,  6.7482996e-01,  6.3907748e-01,  7.9288846e-01,
         0.0000000e+00,  9.8368686e-01,  0.0000000e+00,  1.2401000e+04],
       dtype=float32),
 np.float32(1.0))

In [1]:
import pickle

date = '20231225'
print(date)

file = rf'D:\\L2_DATA_T0_ETF\\train_data\\RAW\\BC_train_data_20250729\\data_dict\\{date}.pkl'
data_dict = pickle.load(open(file, 'rb'))
symbol = []
for k, v in data_dict.items():
    symbol.append(k)
    for k2, v2 in v.items():
        print(f'{k} {k2} {v2.shape}')

print(symbol)

20231225
159934 obs (6, 4)
159934 acts (8194,)
159937 obs (6, 4)
159937 acts (5996,)
518800 obs (6, 4)
518800 acts (5340,)
518880 obs (6, 4)
518880 acts (8520,)
['159934', '159937', '518800', '518880']


In [2]:
train_data_folder = r'D:\\L2_DATA_T0_ETF\\train_data\\RAW\\BC_train_data_20250729\\train_data'
file2 = rf'{train_data_folder}\\{date}.pkl'
ids, mean_std, x, all_raw_data = pickle.load(open(file2, 'rb'))
len(ids), len(mean_std), len(x)

(14029, 14029, 14029)

In [3]:
for code in symbol:
    code_ids = [i for i, _id in enumerate(ids) if _id.startswith(code)]
    print(f'{code} train_data 长度:', len(code_ids) * 2)

159934 train_data 长度: 8196
159937 train_data 长度: 5998
518800 train_data 长度: 5342
518880 train_data 长度: 8522


In [ ]:
from dl_helper.rl.rl_env.lob_trade.lob_env import LOB_trade_env
from dl_helper.rl.rl_utils import date2days, days2date
from dl_helper.rl.rl_env.lob_trade.lob_expert import LobExpert_file
from dl_helper.rl.rl_env.lob_trade.lob_const import USE_CODES, STD_REWARD

import numpy as np

need_pos_0 = True
need_pos_1 = True

his_len = 50
data_config = {
    # 此处的参数不重要 
    'his_len': his_len,# 每个样本的 历史数据长度
    # 此处的参数不重要 
    'need_cols': [item for i in range(1) for item in [f'BASE卖{i+1}价', f'BASE卖{i+1}量', f'BASE买{i+1}价', f'BASE买{i+1}量']],
}
env = LOB_trade_env(
    config={
        'his_len': data_config['his_len'],
        'need_cols': data_config['need_cols'],
        'use_symbols': symbol,
        'random_begin_in_day': False,
        'train_folder': r'C:\Users\lh\Desktop\temp\lob_env',
        'train_title': 'temp',
    },
    debug_obs_date=date2days(date),
    debug_init_pos=0,
    data_folder=train_data_folder,
)

data_dict = {}
wait_symbol = symbol.copy()
while wait_symbol:
    # expert = LobExpert_file(data_folder=train_data_folder, logout=False)
    
    obss = []
    obs, info = env.reset()

    _symbol_str = USE_CODES[int(obs[-4])]
    print((obs[-4], _symbol_str))
    if _symbol_str in wait_symbol:
        wait_symbol.remove(_symbol_str)
    else:
        # 说明当天的数据遍历完成
        print(f'{date} 当天数据遍历完成')
        break

    done = False
    while not done:
        obss.append(obs[-4:].copy())
        obs, reward, terminated, truncated, info = env.step(1)
        done = terminated or truncated

    single_obs_num = len(obss)
    print(f'标的 {_symbol_str} 当天样本数量: {single_obs_num * 2}', flush=True)

    # 构造 obs - 使用更高效的方式
    no_pos = np.array(obss) # pos == 0 的部分
    has_pos = no_pos.copy()  # pos == 1 的部分
    has_pos[:, -2] = 1

    del obss

    done_obs = []
    done_acts = []
    # balance_del_idx = []

    parts_list = []
    if need_pos_0:
        parts_list.append(no_pos)
    if need_pos_1:
        parts_list.append(has_pos)
    if _symbol_str not in data_dict:
        data_dict[_symbol_str] = {}
    for obs in parts_list:
        # 构造 acts
        acts = np.zeros(single_obs_num, dtype=np.int8)# 等待专家填充
        for i in range(single_obs_num):
            _obs = obs[i]
            # _act = expert.get_action(_obs)
            _act = 0
            acts[i] = _act

        # 添加 原始全样本 到完成列表
        done_obs.append(obs[:, -3:])
        done_acts.append(acts)

    # 合并数据
    data_dict[_symbol_str]['obs'] = np.concatenate(done_obs)
    data_dict[_symbol_str]['acts'] = np.concatenate(done_acts)
    # data_dict[_symbol_str]['balance_del_idx'] = np.concatenate(balance_del_idx)

2025-08-06 09:37:48 | lob_env.py:__init__:1493 - [1011805360] init logger: C:\Users\lh\logs\temp_20250806.log
2025-08-06 09:37:48 | lob_env.py:__init__:124 - [train] debug_date: ['20231225']
2025-08-06 09:37:48 | lob_env.py:__init__:177 - [train] data_producer init done
2025-08-06 09:37:48 | lob_env.py:__init__:1553 - [1011805360][train] init env done
2025-08-06 09:37:48 | lob_env.py:reset:1863 - [1011805360][train] reset
2025-08-06 09:37:48 | lob_env.py:_pre_files:259 - [train] prepare files: ['20231225.pkl']
2025-08-06 09:37:48 | lob_env.py:_load_data:278 - [train] load date file: 20231225.pkl
2025-08-06 09:37:49 | lob_env.py:_load_data:366 - [train] init idxs: [[np.int64(0), np.int64(4097), 2], [np.int64(4098), np.int64(7096), 1], [np.int64(7097), np.int64(9767), 3], [np.int64(9768), np.int64(14028), 0]]
2025-08-06 09:37:49 | lob_env.py:reset:1888 - acc reset: 0
(np.float32(2.0), '159934')
2025-08-06 09:37:50 | lob_env.py:step:1741 - [1011805360][train] total sample: 500
2025-08-06 