In [101]:
import pandas as pd
import torch

In [102]:
rand_cols = torch.randint(0, 1, (1, 5))
for i in range(1):
    r = torch.randperm(10)[:5].sort().values
    rand_cols[i] = r
rand_cols = rand_cols.unsqueeze(1).expand(-1, 4, -1)
print(rand_cols.shape)
rand_cols

torch.Size([1, 4, 5])


tensor([[[4, 6, 7, 8, 9],
         [4, 6, 7, 8, 9],
         [4, 6, 7, 8, 9],
         [4, 6, 7, 8, 9]]])

In [103]:
# [1, 10, 4]
x = torch.Tensor([
    [[1, 2, 3, 4]] * 10
])

for i in range(10):
    x[0,i,0] = i

print(x.shape)
x

torch.Size([1, 10, 4])


tensor([[[0., 2., 3., 4.],
         [1., 2., 3., 4.],
         [2., 2., 3., 4.],
         [3., 2., 3., 4.],
         [4., 2., 3., 4.],
         [5., 2., 3., 4.],
         [6., 2., 3., 4.],
         [7., 2., 3., 4.],
         [8., 2., 3., 4.],
         [9., 2., 3., 4.]]])

In [104]:
# 标准化数据
mean_std = [
    [[1,2],
    [3,4],
    [5,6],
    [7,8],]
]
mean_std = torch.tensor(mean_std, dtype=torch.float)
print(mean_std.shape)
mean_std

torch.Size([1, 4, 2])


tensor([[[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]])

In [105]:
x = torch.transpose(x, 1, 2)
print(x.shape)
x

torch.Size([1, 4, 10])


tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]]])

In [106]:
x = torch.gather(x, dim=2, index=rand_cols)
print(x.shape)
x

torch.Size([1, 4, 5])


tensor([[[4., 6., 7., 8., 9.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]]])

In [107]:
mp = ((x[:, 0, -1] + x[:, 2, -1]) / 2).unsqueeze(1).unsqueeze(1)
mp

tensor([[[6.]]])

In [108]:
vol_cond = torch.tensor([False, True] * 2).unsqueeze(0).unsqueeze(2).expand(1, -1, 5)
vol_cond

tensor([[[False, False, False, False, False],
         [ True,  True,  True,  True,  True],
         [False, False, False, False, False],
         [ True,  True,  True,  True,  True]]])

In [109]:
x = torch.where(~vol_cond, x / mp, x)
x

tensor([[[0.6667, 1.0000, 1.1667, 1.3333, 1.5000],
         [2.0000, 2.0000, 2.0000, 2.0000, 2.0000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [4.0000, 4.0000, 4.0000, 4.0000, 4.0000]]])

In [110]:
x -= mean_std[:, :, :1]
x

tensor([[[-0.3333,  0.0000,  0.1667,  0.3333,  0.5000],
         [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
         [-4.5000, -4.5000, -4.5000, -4.5000, -4.5000],
         [-3.0000, -3.0000, -3.0000, -3.0000, -3.0000]]])

In [111]:
x /= mean_std[:, :, 1:]
x

tensor([[[-0.1667,  0.0000,  0.0833,  0.1667,  0.2500],
         [-0.2500, -0.2500, -0.2500, -0.2500, -0.2500],
         [-0.7500, -0.7500, -0.7500, -0.7500, -0.7500],
         [-0.3750, -0.3750, -0.3750, -0.3750, -0.3750]]])